language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
script:
  - npm run build
  - mv ./build/index.html ./build/200.html
deploy:
  provider: surge
  skip_cleanup: true
  domain: musiviz.surge.sh
  project: ./build/
on:
  branch: master
